services:
  frigate-gotify:
    image: ghcr.io/tomatomonster69/frigate-gotify:latest
    container_name: frigate-gotify
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    ports:
      - "80:80"
    networks:
      - frigate-network
    volumes:
      - frigate-gotify-config:/app/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  frigate-network:
    driver: bridge

volumes:
  frigate-gotify-config:
    driver: local
